"""empty message

Revision ID: 1d8e854522be
Revises: None
Create Date: 2015-05-30 19:44:16.033626

"""

# revision identifiers, used by Alembic.
revision = '1d8e854522be'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    ### end Alembic commands ###
