"""empty message

Revision ID: 23ffcb1ca4a1
Revises: 1d8e854522be
Create Date: 2015-05-31 09:42:00.661471

"""

# revision identifiers, used by Alembic.
revision = '23ffcb1ca4a1'
down_revision = '1d8e854522be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
